steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'prod', '--tag', 'us.gcr.io/$PROJECT_ID/libpostal-api:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/libpostal-api:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'container'
  - 'images'
  - 'add-tag'
  - 'us.gcr.io/$PROJECT_ID/libpostal-api:$COMMIT_SHA'
  - 'us.gcr.io/$PROJECT_ID/libpostal-api:latest'


- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:0.13.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "terraform/$BRANCH_NAME/" ]; then
        cd terraform/$BRANCH_NAME
        terraform init
      else
        for dir in terraform/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.13.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform/$BRANCH_NAME/" ]; then
        cd terraform/$BRANCH_NAME
        terraform plan
      else
        for dir in terraform/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.13.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform/$BRANCH_NAME/" ]; then
        cd terraform/$BRANCH_NAME      
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]


# Deploy container image to Cloud Run
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: gcloud
#  args:
#  - 'run'
#  - 'deploy'
#  - 'thermostat-agent'
#  - '--image'
#  - 'us.gcr.io/$PROJECT_ID/thermostat-agent:$COMMIT_SHA'
#  - '--region'
#  - 'us-east4'
#  - '--platform'
#  - 'managed'
#images:
#- 'us.gcr.io/$PROJECT_ID/thermostat-agent:$COMMIT_SHA'